config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'lists#index'

  resources :lists do
  	resources :simple_tasks, :temporal_tasks, :long_tasks
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	has_many :tasks, dependent: :destroy
	validates :name, presence: true
	validates :url, uniqueness: true

	before_validation(on: :create) do
		if !self.name.nil? 
			self.url=self.name.parameterize
		end
		if !self.name.nil? && self.url==""
			self.url=SecureRandom.hex[0,10].downcase
		end		
	end

	def to_param
		url
	end

end

app/models/long_task.rb
class LongTask < Task
	validates :percentage, presence: true
	validates :percentage, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100 }
end

app/models/simple_task.rb
class SimpleTask < Task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list, :touch => true
  validates :description, presence: true


  def <=>(another_task)

  	if self.priority=="High"
  		aux=1
  	elsif self.priority=="Medium"
  		aux=2
  	else
  		aux=3
  	end

  	if another_task.priority=="High"
  		auxanother=1
  	elsif another_task.priority=="Medium"
  		auxanother=2
  	else
  		auxanother=3
  	end

  	aux<=>auxanother

	end

  def should_appear?
    true
  end
end

app/models/temporal_task.rb
class TemporalTask < Task	
	validates :validation_start, presence: true
	validates :validation_end, presence: true

	before_save do
		if self.validation_end < Date.today
			changeState
		end
	end

	validates :validation_start, date: { before: :validation_end }

	def should_appear?

		#&& self.state!= 'Expired' could not be if i want to show expired tasks in that range

		if (self.validation_start < Date.today) && (self.validation_end > Date.today) && self.state != 'Expired'
			true
		elsif
			self.validation_end < Date.today && self.state != 'Expired'
			changeState
			self.save
			false
		else
			if self.state == 'Expired'
				false
			end
		end
	end

	def changeState
		self.state = 'Expired'	
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :findlist

	def index

		if !(cookies[:lists].nil?)
			@lists=Array.new()

			(cookies[:lists]).split(',').each do |url|

				@lists << List.find_by(url: "#{url}")

	    	end
	  		
	  	end
	end

	def show
		if @list.nil?
			render 'nolist'
		end
	end

	def new
	  @list=List.new
	end

	def edit
	end

	def create
	  @list = List.new(list_params)
	 
	  if @list.save
	  	if !(cookies[:lists].nil?)
	  		a=(cookies[:lists]).split(',')
	  		if (a.size<5)
		  		stuff=cookies[:lists] + ',' + @list.url
		  		cookies[:lists]= stuff
		  	else

		  		a.shift
		  		a.push @list.url
		  		a=a.join(',')
		  		cookies[:lists]=a	
		  	end
		else
			cookies[:lists]=@list.url
		end
	  	redirect_to @list
	  
	  else
	  	render 'new'
	  end
	end

	def update
	 
	  if @list.update(list_params)
	    redirect_to @list
	  else
	    render 'edit'
	  end
	end

	def destroy
	  if !(cookies[:lists].nil?)	
		  a=(cookies[:lists]).split(',')
		  a.delete(@list.url)

		  if (a.size>0)
		  	a=a.join(',')
		  	cookies[:lists]=a
		  else
		  	cookies.delete :lists
		  end
	  end
	  

	  @list.destroy
	 
	  redirect_to lists_path
	end

	
	 
	private

	  def list_params
	    params.require(:list).permit(:name, :url)
	  end

	  def findlist
	    url=params[:id]
	    @list = List.find_by(url: "#{url}")
	  end


end

app/controllers/long_tasks_controller.rb
class LongTasksController < ApplicationController
	before_action :findparent
	before_action :findtask, only: [:update, :edit, :destroy]
	
	def new
		@longTask=LongTask.new
	end

	def edit
	end

  	def create

	  	@longTask=LongTask.new(task_params)

		@longTask.list_id=@list.id

		if @longTask.save

			redirect_to list_path(@list)
		else
			render 'new'
		end
	end

	def update
	  if @longTask.update(task_params)
	    redirect_to @list
	  else
	    render 'edit'
	  end
	end
	

	def destroy
	    @longTask.destroy
	    redirect_to list_path(@list)
	end


  private

  def findtask
  	@longTask=LongTask.find(params[:id])
  end

  def findparent
	  url=params[:list_id]
	  @list = List.find_by(url: "#{url}")
	end

  def task_params
  	params.require(:long_task).permit(:description, :state, :priority, :percentage)
	end
end

app/controllers/simple_tasks_controller.rb
class SimpleTasksController < ApplicationController
	before_action :findparent
	before_action :findtask, only: [:update, :edit, :destroy]
	
	def new
		@simpleTask=SimpleTask.new
	end

	def edit
	end

  	def create

	  	@simpleTask=SimpleTask.new(task_params)

		@simpleTask.list_id=@list.id

		if @simpleTask.save

			redirect_to list_path(@list)
		else
			render 'new'
		end
	end

	def update
	  if @simpleTask.update(task_params)
	    redirect_to @list
	  else
	    render 'edit'
	  end
	end
	

	def destroy
	    @simpleTask.destroy
	    redirect_to list_path(@list)
	end


  private

  def findtask
  	@simpleTask=SimpleTask.find(params[:id])
  end

  def findparent
	  url=params[:list_id]
	  @list = List.find_by(url: "#{url}")
	end

  def task_params
  	params.require(:simple_task).permit(:description, :state, :priority)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/temporal_tasks_controller.rb
class TemporalTasksController < ApplicationController
	before_action :findparent
	before_action :findtask, only: [:update, :edit, :destroy]
	
	def new
		@temporalTask=TemporalTask.new
	end

	def edit
	end

  	def create

	  	@temporalTask=TemporalTask.new(task_params)

		@temporalTask.list_id=@list.id
		
		if @temporalTask.save

			redirect_to list_path(@list)
		else
			render 'new'
		end
	end

	def update
	  if @temporalTask.update(task_params)
	    redirect_to @list
	  else
	    render 'edit'
	  end
	end
	

	def destroy
	    @temporalTask.destroy
	    redirect_to list_path(@list)
	end


  private

  def findtask
  	@temporalTask=TemporalTask.find(params[:id])
  end

  def findparent
	  url=params[:list_id]
	  @list = List.find_by(url: "#{url}")
	end

  def task_params
  	params.require(:temporal_task).permit(:description, :state, :priority, :validation_start, :validation_end)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/long_tasks_helper.rb
module LongTasksHelper
end

app/helpers/simple_tasks_helper.rb
module SimpleTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/temporal_tasks_helper.rb
module TemporalTasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoLists App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="main-container" class="container-fluid">
  		<div id="main-content" class="col-xs-12">
        <div class="container">
      	 <%= yield %>
        </div>
     	</div>
	   </div>

    <div id="footer">
      <div class="container text-center">
        <p class="text-muted credit">Handmade with Love</p>
      </div>
    </div>


  </body>
</html>

app/views/lists/_form.html.erb
<div class="form-group">

<%= form_for @list do |f| %>

  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form-control" %>
  </p>
 
  <p>
    <%= f.submit :class => "btn btn-success" %>
  </p>

  <br><br>
<% end %>

</div>

app/views/lists/_tasks.html.erb
  <div class="row">
    <div class="col-sm-3"> 
    <div class="panel panel-success">
      <div class="panel-heading">New Simple Task</div>
      <div class="panel-body">Simple Tasks are tasks with a Description, State and Priority to say how important the task is
        <br><br>
        <%= link_to 'New Simple Task', new_list_simple_task_path(@list), :class => "btn btn-success" %>
      </div>

    </div>
    </div>
    <div class="col-sm-3">
     <div class="panel panel-default">
      <div class="panel-heading">New Temporal Task</div>
      <div class="panel-body">Temporal Tasks are like Simple Tasks, but you can also define a Start and Expiration date
        <br><br>
        <%= link_to 'New Temporal Task', new_list_temporal_task_path(@list), :class => "btn btn-info" %>
      </div>
    </div>
    </div>
    <div class="col-sm-3">
     <div class="panel panel-info">
      <div class="panel-heading">New Long Task</div>
      <div class="panel-body">Long Tasks will take some time to complete, so you can define a percentage of completion
        <br><br>
        <%= link_to 'New Long Task', new_list_long_task_path(@list), :class => "btn btn-primary" %>
      </div>
    </div>
    </div>
  </div>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/lists/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to ToDoList app!</h1>
  <p>Most cutie page to keep your mind sharp</p> 
</div>

<div class="col-sm-12 text-center">
  <h3>Wanna make some ToDoLists?</h3>
  <p><%= link_to 'Make New List!', new_list_path, :class => "btn btn-success" %></p>
</div>


<h3>Last Lists Created by You</h3>
<% if defined?(@lists)  %>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
  <% @lists.each do |list| %>
    <tr>
      <td><%= list.name %></td>
      <td><%= list.url %></td>
      <td><%= link_to 'Show', list_path(list) %></td>
      <td><%= link_to 'Edit', edit_list_path(list) %></td>
      <td><%= link_to 'Destroy', list_path(list),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>

  
  <% else %>

  <h4>No lists yet, get started by adding some New List</h4>

  <% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path, :class => "btn btn-info"%>

app/views/lists/nolist.html.erb
<div class="container">
  <h2>No list found!</h2>
    <div class="panel panel-warning">
      <div class="panel-heading">The list name you provided does not exist</div>
      <div class="panel-body">Maybe wrong url? Go to the index to check your lists!</div>
    </div>

    <%= link_to 'Go index', lists_path, :class => "btn btn-success"%>
</div>

app/views/lists/show.html.erb
<h1>Checking out List</h1>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>
 
<p>
  <strong>Url:</strong>
  <%= @list.url %>
</p>

<p>
  <strong>Created:</strong>
  <%= @list.created_at %>
</p>

<p>
  <strong>Modified:</strong>
  <%= @list.updated_at %>
</p>


<%= link_to 'Edit List Name', edit_list_path(@list), :class => "btn btn-info" %>

<h2>This List has the following Tasks</h2>

<table class="table">
  <tr>
    <th>Type</th>
    <th>Description</th>
    <th>State</th>
    <th>Priority</th>
    <th></th>
    <th></th>
  </tr>


  <% @list.tasks.sort.each do |task| %>
    <% if task.should_appear? %>
    <tr>
      <td><%= task.type %></td>
      <td><%= task.description %></td>
      <td><%= task.state %></td>
      <td><%= task.priority %></td>


      <td><%= link_to 'Edit', url_for([:edit, @list, task]) %></td>
      <td><%= link_to 'Destroy', [task.list, task],
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  <% end %>
</table>


<h2>Add a new task:</h2>

<%= render 'tasks' %>

<%= link_to 'Back', lists_path, :class => "btn btn-info" %>

app/views/long_tasks/_form.html.erb
<div class="form-group">


  <% if @longTask.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@longTask.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @longTask.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for [@list, @longTask] do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description, :class => "form-control" %>
  </p>
  <p>
    <%= f.label :state %><br>
    <%= f.select :state, options_for_select(['Pendient', 'Done', 'In course'], :selected => @longTask.state), {}, class: "form-control" %>
  </p>
  <p>
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(['High', 'Medium', 'Low'], :selected => @longTask.priority), {}, class: "form-control" %>
  </p>
  <p>
    <%= f.label :percentage %><br>
    <%= f.number_field :percentage, min: 0, max: 100, step: :any %>
  </p>

  <p><br>
    <%= f.submit  :class => "btn btn-success"%>
  </p>
<% end %>

</div>

app/views/long_tasks/edit.html.erb
<h1>Edit Long Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/long_tasks/new.html.erb
<h1>New Long Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/simple_tasks/_form.html.erb
<div class="form-group">


  <% if @simpleTask.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@simpleTask.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @simpleTask.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for [@list, @simpleTask] do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description, :class => "form-control" %>
  </p>
  <p>
    <%= f.label :state %><br>
    <%= f.select :state, options_for_select(['Pendient', 'Done'], :selected => @simpleTask.state), {}, class: "form-control" %>
  </p>
  <p>
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(['High', 'Medium', 'Low'], :selected => @simpleTask.priority), {}, class: "form-control" %>
  </p>
  <p><br>
    <%= f.submit  :class => "btn btn-success"%>
  </p>
<% end %>

</div>

app/views/simple_tasks/edit.html.erb
<h1>Edit Simple Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/simple_tasks/new.html.erb
<h1>New Simple Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/temporal_tasks/_form.html.erb
<div class="form-group">


  <% if @temporalTask.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@temporalTask.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @temporalTask.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for [@list, @temporalTask] do |f| %>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description, :class => "form-control" %>
  </p>
  <p>
    <%= f.label :state %><br>
    <%= f.select :state, options_for_select(['Pendient', 'Done', 'Expired'], :selected => @temporalTask.state), {}, class: "form-control" %>
  </p>
  <p>
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(['High', 'Medium', 'Low'], :selected => @temporalTask.priority), {}, class: "form-control" %>
  </p>
  <p>

  <%= f.label :validation_start %><br>
  <%= f.text_field :validation_start, 'data-behaviour' => 'datepicker' %>
  </p>

  <p>
  <%= f.label :validation_end %><br>
  <%= f.text_field :validation_end, 'data-behaviour' => 'datepicker' %>
  </p>


  <script>
  $(document).on("focus", "[data-behaviour~='datepicker']", function(e){
      $(this).datepicker({"format": "yyyy-mm-dd", "weekStart": 1, "autoclose": true});
  });

  </script>

  <p><br>
    <%= f.submit  :class => "btn btn-success"%>
  </p>
<% end %>

</div>

app/views/temporal_tasks/edit.html.erb
<h1>Edit Temporal Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/temporal_tasks/new.html.erb
<h1>New Temporal Task</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(@list), :class => "btn btn-info" %>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to ToDoList app!</h1>
  <p>most cutie page to keep your mind on the flow</p> 
</div>

<div class="col-sm-12 text-center">
  <h3>Wanna make some ToDoLists?</h3>
  <p><%= link_to 'Make and View Lists!', controller: 'lists' %></p>
</div>